version: "3"
services:
  web:
    build: nginx
    volumes:
        - ../site:/var/www/site
        - ./data/var/log/nginx:/var/log/nginx
        - ./data/var/log/nginx/site:/var/log/nginx/site
#        - ./nginx/ssl:/etc/nginx/ssl
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - 80:80
#        - 443:443
    depends_on:
      - php
    networks:
      - frontend
      - backend
  
  php:
    build: php-fpm
    volumes:
        - ../site:/var/www/site
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    environment:
        XDEBUG_CONFIG: remote_host=10.254.254.254
    depends_on:
      - mysql
    dns: 8.8.8.8
    networks:
      - backend
      - frontend

  adminer:
    build: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  mysql:
    build: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql # сохранение файлов БД на хосте
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: site
    networks:
      - backend
      - frontend

  rabbitmq:
    build: rabbitmq
    restart: always
    #command: "rabbitmq-plugins enable rabbitmq_management"
    networks:
      - backend
      - frontend
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    build: redis
    restart: always
    volumes:
     - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - backend
      - frontend

networks:
  frontend:
    external:
      name: frontend-site
  backend:
