version: "3"
services:
  web:
    build: nginx
    volumes:
        - ${SITE_DIR}:/var/www/${SITE_NAME}
        - ./data/var/log/nginx:/var/log/nginx
        - ./data/var/log/nginx/${SITE_NAME}:/var/log/nginx/${SITE_NAME}
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    ports:
        - 80:80
#        - 443:443
    depends_on:
      - php
    networks:
      - frontend
      - backend
  
  php:
    build: php-fpm
    volumes:
        - ${SITE_DIR}:/var/www/${SITE_NAME}
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    environment:
        XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  adminer:
    build: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  mysql:
    build: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql # save db files on host mashine
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    networks:
      - backend
      - frontend

  rabbitmq:
    build: rabbitmq
    networks:
      - backend
      - frontend
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  redis:
    build: redis
    volumes:
     - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - backend
      - frontend

networks:
  frontend:
    external:
      name: frontend-${SITE_NAME}
  backend:
