FROM nginx:1.9.0

#COPY ./backend.conf /etc/nginx/conf.d/backend.conf
COPY ./frontend.conf /etc/nginx/conf.d/frontend.conf
COPY ./name.part /etc/nginx/conf.d/name.part
COPY ./server.part /etc/nginx/conf.d/server.part
